name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-client-tests:
    name: Run Tests for Client
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Install Node.js dependencies
        run: yarn
        working-directory: client

      - name: Run Test
        run: yarn test
        working-directory: client

  run-server-tests:
    name: Run Tests for Server
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Node.js dependencies
        run: yarn
        working-directory: server

      - name: Test with Firestore emulator
        run: ./node_modules/.bin/firebase emulators:exec "yarn test" --only firestore
        working-directory: server
